.TH LIBRECRYPT_WIPE 3 LIBRECRYPT
.SH NAME
librecrypt_wipe - Securely erase a memory buffer

.SH SYNOPSIS
.nf
#include <librecrypt.h>

void \fBlibrecrypt_wipe\fP(void *\fIbuffer\fP, size_t \fIsize\fP);
.fi
.PP
Link with
.IR -lrecrypt .

.SH DESCRIPTION
The
.BR librecrypt_wipe ()
function securely erases
.I size
bytes from
.IR buffer .

.SH RETURN VALUES
None.

.SH ERRORS
The
.BR librecrypt_wipe ()
function cannot fail.

.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.PP
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR librecrypt_wipe ()
T}	Thread safety	MT-Safe
T{
.BR librecrypt_wipe ()
T}	Async-signal safety	AS-Safe
.TE
.sp

.SH HISTORY
The
.BR librecrypt_wipe ()
function was introduced in version 1.0 of
.BR librecrypt .

.SH SEE ALSO
.BR librecrypt (7),
.BR librecrypt_wipe_str (3)
