/* See LICENSE file for copyright and license details. */
#include "common.h"
#ifndef TEST


const int librecrypt_version_major = LIBRECRYPT_VERSION_MAJOR;
const int librecrypt_version_minor = LIBRECRYPT_VERSION_MINOR;
const int librecrypt_version_patch = LIBRECRYPT_VERSION_PATCH;


#else


int
main(void)
{
	int i, j, k;

	SET_UP_ALARM();
	INIT_RESOURCE_TEST();

	EXPECT(librecrypt_version_major == LIB_MAJOR);
	EXPECT(librecrypt_version_minor == LIB_MINOR);
	EXPECT(librecrypt_version_patch == LIB_PATCH);
	EXPECT(LIBRECRYPT_VERSION_MAJOR == LIB_MAJOR);
	EXPECT(LIBRECRYPT_VERSION_MINOR == LIB_MINOR);
	EXPECT(LIBRECRYPT_VERSION_PATCH == LIB_PATCH);

	EXPECT(LIBRECRYPT_VERSION_CMP_BUILD(LIB_MAJOR, LIB_MINOR, LIB_PATCH) == 0);
	EXPECT(LIBRECRYPT_VERSION_CMP_LINK(LIB_MAJOR, LIB_MINOR, LIB_PATCH) == 0);
	for (i = 1; i <= 3; i++) {
		EXPECT(LIBRECRYPT_VERSION_CMP_BUILD(LIB_MAJOR, LIB_MINOR, LIB_PATCH - i) == -1);
		EXPECT(LIBRECRYPT_VERSION_CMP_BUILD(LIB_MAJOR, LIB_MINOR, LIB_PATCH + i) == +1);
		EXPECT(LIBRECRYPT_VERSION_CMP_LINK(LIB_MAJOR, LIB_MINOR, LIB_PATCH - i) == -1);
		EXPECT(LIBRECRYPT_VERSION_CMP_LINK(LIB_MAJOR, LIB_MINOR, LIB_PATCH + i) == +1);
		for (j = -3; j <= 3; j++) {
			EXPECT(LIBRECRYPT_VERSION_CMP_BUILD(LIB_MAJOR, LIB_MINOR - i, LIB_PATCH + j) == -2);
			EXPECT(LIBRECRYPT_VERSION_CMP_BUILD(LIB_MAJOR, LIB_MINOR + i, LIB_PATCH + j) == +2);
			EXPECT(LIBRECRYPT_VERSION_CMP_LINK(LIB_MAJOR, LIB_MINOR - i, LIB_PATCH + j) == -2);
			EXPECT(LIBRECRYPT_VERSION_CMP_LINK(LIB_MAJOR, LIB_MINOR + i, LIB_PATCH + j) == +2);
			for (k = -3; k <= 3; k++) {
				EXPECT(LIBRECRYPT_VERSION_CMP_BUILD(LIB_MAJOR - i, LIB_MINOR + j, LIB_PATCH + k) == -3);
				EXPECT(LIBRECRYPT_VERSION_CMP_BUILD(LIB_MAJOR + i, LIB_MINOR + j, LIB_PATCH + k) == +3);
				EXPECT(LIBRECRYPT_VERSION_CMP_LINK(LIB_MAJOR - i, LIB_MINOR + j, LIB_PATCH + k) == -3);
				EXPECT(LIBRECRYPT_VERSION_CMP_LINK(LIB_MAJOR + i, LIB_MINOR + j, LIB_PATCH + k) == +3);
			}
		}
	}

	STOP_RESOURCE_TEST();
	return 0;
}


#endif
