.TH LIBRECRYPT_GET_USER_DATA 3 LIBRECRYPT
.SH NAME
librecrypt_get_user_data - Retrieve application-defined data

.SH SYNOPSIS
.nf
#include <librecrypt.h>

void \fBlibrecrypt_get_user_data\fP(const LIBRECRYPT_CONTEXT *\fIctx\fP, void *\fIuser\fP);
.fi
.PP
Link with
.IR -lrecrypt .

.SH DESCRIPTION
The
.BR librecrypt_get_user_data ()
function returns a pointer to application-defined
data, stored using the
.BR librecrypt_set_user_data (3)
function, inside the
.IR ctx .

.SH RETURN VALUES
The
.BR librecrypt_get_user_data ()
function returns a pointer stored in
.I ctx
by the application, or
.I NULL
if no pointer or the
.I NULL
pointer was stored.

.SH ERRORS
The
.BR librecrypt_get_user_data ()
function cannot fail.

.SH HISTORY
The
.BR librecrypt_get_user_data ()
function was introduced in version 1.1 of
.BR librecrypt .

.SH SEE ALSO
.BR librecrypt (7),
.BR librecrypt_set_user_data (3),
.BR librecrypt_set_custom_algorithms (3)
