include $(TEST_INCLUDE_PREFIX)common-config.mk

TEST_CPPFLAGS = -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_XOPEN_SOURCE=700 -D_GNU_SOURCE\
                $(IMPLEMENT_MMAP_CPPFLAGS) -DWITH_BACKTRACE
TEST_CFLAGS   = -g
TEST_LDFLAGS  = -lunwind -ldw

OBJ_BACKTRACE = libtest_print_backtrace.o
